[project]
name = "sedfitter"
authors = [
    {name = "Thomas Robitaille", email = "thomas.robitaille@gmail.com"},
]
license = "BSD-2-Clause"
license-files = ["LICENSE"]
description = "SED Fitter in Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.23.2",
    "scipy>=1.9",
    "matplotlib>=3.6",
    "astropy>=5.2",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
]
docs = [
    "sphinx",
    "sphinx-automodapi",
    "numpydoc",
]

[project.urls]
Homepage = "https://github.com/astrofrog/sedfitter"

[build-system]
requires = [
    "setuptools>=77",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
namespaces = false

[tool.setuptools.package-data]
"sedfitter.sed.tests" = ["data/*.fits.gz"]
"sedfitter.filter.tests" = ["data/*.txt"]
"sedfitter.utils.tests" = ["data/*.conf", "data/*.par"]

[tool.setuptools_scm]
write_to = "sedfitter/version.py"
write_to_template = """
# Note that we need to fall back to the hard-coded version if either
# setuptools_scm can't be imported or setuptools_scm can't determine the
# version, so we catch the generic 'Exception'.
try:
    from setuptools_scm import get_version
    version = get_version(root='..', relative_to=__file__)
except Exception:
    version = '{version}'
"""

[tool.pytest.ini_options]
testpaths = ["sedfitter"]

[tool.coverage.run]
omit = [
    "sedfitter/conftest.py",
    "sedfitter/tests/*",
    "sedfitter/*/tests/*",
    "sedfitter/version*",
    "*/sedfitter/conftest.py",
    "*/sedfitter/tests/*",
    "*/sedfitter/*/tests/*",
    "*/sedfitter/version*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "except ImportError",
    "raise AssertionError",
    "raise NotImplementedError",
    "def main\\(.*\\):",
    "pragma: py{ignore_python_version}",
    "def _ipython_key_completions_",
]
