#!/usr/bin/env python

import sys

import sedfitter

def _usage(*args):

    if len(args) == 1:
        print "\n    ERROR: " + args[0] + ''

    print '''
    Usage: sed_filter_output [arguments]

    Required arguments :
      input=filename     - the input file

    then one and only one of the following:
      chi=value          - constrain using total chisquared
      cpd=value          - constrain using chisquared per datapoint
    '''
    sys.exit(0)

if len(sys.argv) == 1:
    _usage()

options = {}
for option in sys.argv[1:]:
    try:
        key, value = option.split('=')
    except:
        _usage("Invalid option %s" % option)
    options[key] = value

if not 'input' in options:
    _usage("Argument input is required")

if (not 'cpd' in options and not 'chi' in options) \
    or ('cpd' in options and 'chi' in options):
    _usage("One of cpd or chi is required")

# Open input and output file

if 'chi' in options:
    sedfitter.filter_output(input=options['input'], chi=float(options['chi']))
else:
    sedfitter.filter_output(input=options['input'], cpd=float(options['cpd']))
    
