name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      envs: |
        - linux: py39-test-oldestdeps
        - macos: py310-test
        - windows: py311-test
        - linux: py312-test-devdeps
  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs sedfitter
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
