name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      envs: |
        - linux: py38-test-oldestdeps
        - macos: py39-test
        - windows: py310-test
        - linux: py311-test
  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs sedfitter
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
